import streamlit as st
import tensorflow as tf
import numpy as np
import os
from PIL import Image
from google import genai
from google.genai import types
from dotenv import load_dotenv

from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
import io

# ==========================================
# 0. PDF GENERATOR FUNCTION (PURE ENGLISH)
# ==========================================
def generate_pdf(predictions_text, gemini_report_en):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
    story = []
    
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'TitleStyle', parent=styles['Heading1'], fontName='Helvetica-Bold', fontSize=22, alignment=0, spaceAfter=20
    )
    section_style = ParagraphStyle(
        'SectionStyle', parent=styles['Heading2'], fontName='Helvetica-Bold', fontSize=14, spaceBefore=18, spaceAfter=10
    )
    text_style = ParagraphStyle(
        'TextEn', parent=styles['Normal'], fontName='Helvetica', fontSize=10.5, leading=15, spaceAfter=6
    )
    disclaimer_style = ParagraphStyle(
        'Disclaimer', parent=styles['Italic'], fontName='Helvetica-Oblique', fontSize=8.5, alignment=1, spaceBefore=40
    )

    # כותרת הדוח
    story.append(Paragraph("MedAI - Clinical Analysis Report", title_style))
    story.append(Spacer(1, 10))
    
    # תוצאות המודל
    story.append(Paragraph("1. CNN Computer Vision Predictions:", section_style))
    for line in predictions_text:
        story.append(Paragraph(line, text_style))
        
    story.append(Spacer(1, 10))
    
    # הניתוח של ג'מיני באנגלית
    story.append(Paragraph("2. AI Clinical Synthesis & Visual Analysis:", section_style))
    paragraphs = gemini_report_en.split('\n')
    for para in paragraphs:
        if para.strip():
            clean_para = para.replace("**", "").replace("*", "").strip()
            story.append(Paragraph(clean_para, text_style))
            
    # דיסקליימר רפואי
    story.append(Paragraph(
        "Disclaimer: This report is generated by an artificial intelligence research system for educational and decision-support purposes only. It does not constitute formal medical advice or diagnosis. Please consult a board-certified dermatologist immediately for any clinical concerns.", 
        disclaimer_style
    ))
    
    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()

load_dotenv()

# ==========================================
# 1. INITIALIZE GEMINI VLM API
# ==========================================
API_KEY = os.getenv("GEMINI_API_KEY")
client = genai.Client(api_key=API_KEY)

if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

# ==========================================
# 2. LOAD LOCAL EFFICIENTNET MODEL
# ==========================================
@st.cache_resource
def load_local_model():
    base_model = tf.keras.applications.EfficientNetB0(
        weights=None, include_top=False, input_shape=(224, 224, 3)
    )
    x = base_model.output
    x = tf.keras.layers.GlobalAveragePooling2D()(x)
    x = tf.keras.layers.Dense(128, activation="relu")(x)
    predictions_layer = tf.keras.layers.Dense(7, activation="softmax")(x)
    
    model = tf.keras.models.Model(inputs=base_model.input, outputs=predictions_layer)
    
    weights_path = "skin_model_weights.weights.h5"
    if os.path.exists(weights_path):
        model.load_weights(weights_path)
    return model

try:
    model = load_local_model()
    class_labels = ['akiec', 'bcc', 'bkl', 'df', 'mel', 'nv', 'vasc']
    class_descriptions = {
        'akiec': 'Actinic Keratosis (טרום סרטני)',
        'bcc': 'Basal Cell Carcinoma (סרטן תאי בסיס)',
        'bkl': 'Benign Keratosis (נגע שפיר)',
        'df': 'Dermatofibroma (פיברומה של העור - שפיר)',
        'mel': 'Melanoma (מלנומה - ממאיר חשוד)',
        'nv': 'Melanocytic Nevus (נקודת חן רגילה/שומה)',
        'vasc': 'Vascular Lesion (נגע בכלי דם)'
    }
    class_names_en = {
        'akiec': 'Actinic Keratosis (Pre-cancerous)',
        'bcc': 'Basal Cell Carcinoma (BCC)',
        'bkl': 'Benign Keratosis',
        'df': 'Dermatofibroma',
        'mel': 'Melanoma (Malignant)',
        'nv': 'Melanocytic Nevus (Mole)',
        'vasc': 'Vascular Lesion'
    }
except Exception as e:
    st.error(f"שגיאה בטעינת המודל המקומי: {e}")

# ==========================================
# 3. STREAMLIT UI DESIGN (HEBREW INTERFACE)
# ==========================================
st.set_page_config(page_title="MedAI - Skin Disease Assistant", layout="wide")

st.markdown("""
<style>
    .stApp { background: linear-gradient(135deg, #F8FAFC 0%, #EEF7FB 100%); color: #0F172A; }
    .main .block-container { max-width: 1180px; padding-top: 2rem; padding-bottom: 3rem; }
    .hero-card { background: linear-gradient(135deg, #0F172A 0%, #075985 55%, #0EA5E9 100%); padding: 34px 38px; border-radius: 24px; color: white; box-shadow: 0 18px 45px rgba(15, 23, 42, 0.18); margin-bottom: 28px; }
    .hero-title { font-size: 42px; font-weight: 800; margin-bottom: 8px; letter-spacing: -0.5px; }
    .hero-subtitle { font-size: 18px; line-height: 1.7; color: #E0F2FE; max-width: 880px; }
    .soft-card { background: white; padding: 24px; border-radius: 20px; border: 1px solid #E2E8F0; box-shadow: 0 10px 30px rgba(15, 23, 42, 0.07); margin-bottom: 18px; }
    .section-title { font-size: 22px; font-weight: 800; color: #0F172A; margin-bottom: 12px; }
    .muted-text { color: #64748B; font-size: 15px; line-height: 1.6; }
    .result-card { background: white; padding: 22px; border-radius: 18px; border: 1px solid #E2E8F0; box-shadow: 0 8px 24px rgba(15, 23, 42, 0.06); text-align: center; min-height: 130px; }
    .result-label { color: #64748B; font-size: 14px; margin-bottom: 8px; font-weight: 600; }
    .result-value { color: #0F172A; font-size: 24px; font-weight: 800; line-height: 1.35; }
    .risk-low { color: #059669; }
    .risk-medium { color: #D97706; }
    .risk-high { color: #DC2626; }
    .report-card { background: white; border-radius: 22px; padding: 28px 32px; border-right: 6px solid #0EA5E9; box-shadow: 0 12px 34px rgba(15, 23, 42, 0.08); line-height: 1.9; font-size: 16px; direction: rtl; text-align: right; white-space: pre-wrap; }
    .disclaimer-box { background: #FFF7ED; border: 1px solid #FED7AA; color: #9A3412; padding: 14px 18px; border-radius: 14px; font-size: 14px; line-height: 1.6; margin-top: 14px; direction: rtl; }
    div[data-testid="stFileUploader"] { background: white; padding: 20px; border-radius: 18px; border: 1px dashed #38BDF8; box-shadow: 0 8px 24px rgba(15, 23, 42, 0.05); }
    .stTabs [data-baseweb="tab-list"] { gap: 10px; background: white; padding: 8px; border-radius: 18px; box-shadow: 0 8px 24px rgba(15, 23, 42, 0.06); }
    .stTabs [data-baseweb="tab"] { border-radius: 14px; padding: 12px 18px; font-weight: 700; }
    .stTabs [aria-selected="true"] { background: #E0F2FE; color: #0369A1; }
    div.stButton > button, div.stDownloadButton > button { border-radius: 14px; border: 0; background: linear-gradient(135deg, #0284C7 0%, #0EA5E9 100%); color: white; font-weight: 700; padding: 0.7rem 1.1rem; }
</style>
""", unsafe_allow_html=True)

st.markdown("""
<div class="hero-card" dir="rtl">
    <div class="hero-title">🩺 MedAI</div>
    <div class="hero-subtitle">
        מערכת חכמה לניתוח נגעי עור: שילוב בין מודל ראייה ממוחשבת מקומי EfficientNetB0 לבין Gemini VLM להפקת דוח קליני וצ'אט המשך בעברית.
    </div>
</div>
""", unsafe_allow_html=True)

uploaded_file = st.file_uploader("העלה תמונה של נגע העור (JPG/PNG)", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert("RGB")

    if "local_prediction_done" not in st.session_state:
        with st.spinner("⏳ המודל המקומי מנתח את התמונה..."):
            img_resized = image.resize((224, 224))
            img_array = np.array(img_resized).astype("float32")
            img_array = np.expand_dims(img_array, axis=0)
            predictions = model.predict(img_array)
            top_index = np.argmax(predictions[0])
            st.session_state.predicted_class = class_labels[top_index]
            st.session_state.confidence = predictions[0][top_index] * 100
            st.session_state.all_predictions = predictions[0]
            st.session_state.local_prediction_done = True

    # ==========================================
    # INDEPENDENT GEMINI IMAGE CLASSIFICATION
    # ==========================================
    if "gemini_prediction_done" not in st.session_state:
        with st.spinner("🤖 Gemini מנתח את התמונה באופן עצמאי..."):
            try:
                gemini_classification_prompt = """
                You are analyzing a dermatology image for an educational AI research system.

                Independently review the image and select the single most visually compatible
                category from the following closed list:

                akiec
                bcc
                bkl
                df
                mel
                nv
                vasc

                Do not use any prediction from another model.
                Do not provide a definitive medical diagnosis.

                Return the answer in EXACTLY this format:

                [CLASS]
                one_class_from_the_list
                [/CLASS]

                [REASON]
                A short explanation in Hebrew based only on visible characteristics
                such as color, border, symmetry, shape and texture.
                [/REASON]
                """

                gemini_classification_response = client.models.generate_content(
                    model="gemini-2.5-flash",
                    contents=[gemini_classification_prompt, image]
                )

                gemini_text = gemini_classification_response.text

                gemini_predicted_class = (
                    gemini_text
                    .split("[CLASS]")[1]
                    .split("[/CLASS]")[0]
                    .strip()
                    .lower()
                    .lower()
                )

                gemini_reason = (
                    gemini_text
                    .split("[REASON]")[1]
                    .split("[/REASON]")[0]
                    .strip()
                )

                allowed_classes = {"akiec", "bcc", "bkl", "df", "mel", "nv", "vasc"}

                if gemini_predicted_class not in allowed_classes:
                    raise ValueError(f"Gemini returned an unsupported class: {gemini_predicted_class}")

                st.session_state.gemini_predicted_class = gemini_predicted_class
                st.session_state.gemini_reason = gemini_reason
                st.session_state.gemini_prediction_done = True

            except Exception as e:
                st.session_state.gemini_predicted_class = "unknown"
                st.session_state.gemini_reason = "לא ניתן היה לקבל סיווג עצמאי תקין מ-Gemini."
                st.session_state.gemini_prediction_done = True
                st.warning(f"לא ניתן היה להשלים את בדיקת Gemini: {e}")

    local_class = st.session_state.predicted_class
    gemini_class = st.session_state.gemini_predicted_class
    local_confidence = st.session_state.confidence

    # בניית הקשר ההשוואה עבור מודל הדו"ח
    comparison_context_instruction = f"""
    Our local CNN predicted: {class_descriptions[local_class]} with {local_confidence:.1f}% confidence.
    Your independent visual classification was: {gemini_class}.
    
    You must include a 'System Consensus Check' at the very start of the report based on these rules:
    - If they MATCH: Note that both systems reached a consensus on {class_descriptions[local_class]}, increasing statistical reliability.
    - If they MISMATCH: Explain clearly but professionally that the local computer-vision pattern (CNN) and the language model's visual synthesis (VLM) show a discrepancy, adding baseline uncertainty.
    """

    if "initial_report_he" not in st.session_state:
        with st.spinner("🤖 מודל השפה (Gemini VLM) מנסח ניתוח קליני מפורט..."):
            try:
                prompt = f"""
                You are an expert clinical dermatologist AI assistant.
                
                {comparison_context_instruction}

                Please review the image visually and generate TWO separate clinical analysis reports following this STRICT structural order:
                1. System Consensus Check: Display the prediction results from both models, compare them, and explain the significance of their agreement or disagreement.
                2. Pathology Explanation: Provide a comprehensive medical breakdown and explanation of the predicted condition (characteristics, visuals).
                3. Recommendations & Next Steps: Outline clinical advice, monitoring steps, and practical guidance.
                4. Medical Disclaimer: State clearly and prominently that this tool does not replace a definitive, professional medical diagnosis.

                Never provide a definitive medical diagnosis. Always recommend consultation with a dermatologist.

                === HEBREW REPORT ===
                Write an extensive, comprehensive clinical report entirely in Hebrew for the user interface. 
                You must structure it with clear headings in Hebrew following the 4 steps above.

                === ENGLISH REPORT ===
                Write the exact same clinical report structured entirely in English (for the downloadable PDF file) following the exact same 4 steps above.

                Format your final answer exactly with these two split markers:
                [HEBREW_START]
                (your structured Hebrew report text here)
                [HEBREW_END]
                [ENGLISH_START]
                (your structured English report text here)
                [ENGLISH_END]
                """

                # הערה: שימוש בפרמטר ה-image שמועלה ישירות במקום נתיב קשיח ללוקאל
                response = client.models.generate_content(model='gemini-2.5-flash', contents=[prompt, image])
                full_text = response.text
                
                try:
                    he_report = full_text.split("[HEBREW_START]")[1].split("[HEBREW_END]")[0].strip()
                    en_report = full_text.split("[ENGLISH_START]")[1].split("[ENGLISH_END]")[0].strip()
                except:
                    he_report = full_text
                    en_report = "Clinical report generation error. Please re-upload image."
                    
                st.session_state.initial_report_he = he_report
                st.session_state.initial_report_en = en_report
                st.session_state.chat_history.append({"role": "assistant", "text": he_report})
            except Exception as e:
                st.error(f"נכשלה הגישה ל-Gemini API: {e}")

    # ==========================================
    # 4. TABS & VISUAL RENDERING
    # ==========================================
    tab_analysis, tab_report, tab_chat = st.tabs(["📊 Analysis", "📄 Clinical Report", "💬 AI Assistant"])

    with tab_analysis:
        st.markdown('<div class="section-title" dir="rtl">תמונת הנגע ותוצאות המודל המקומי</div>', unsafe_allow_html=True)
        col_img, col_summary = st.columns([1, 1.15], gap="large")
        with col_img:
            st.markdown('<div class="soft-card" dir="rtl"><div class="section-title">Uploaded Clinical Image</div>', unsafe_allow_html=True)
            st.image(image, caption="התמונה שהועלתה", use_container_width=True)
            st.markdown('</div>', unsafe_allow_html=True)

        with col_summary:
            predicted_description = class_descriptions[local_class]
            risk_class = "risk-low"
            risk_text = "נמוכה / בינונית"
            if local_class in ["mel", "bcc", "akiec"]:
                risk_class = "risk-high"
                risk_text = "דורש בדיקה רפואית"
            elif local_confidence < 70:
                risk_class = "risk-medium"
                risk_text = "לא חד-משמעי"

            c1, c2, c3 = st.columns(3)
            with c1:
                st.markdown(f"""
                <div class="result-card" dir="rtl">
                    <div class="result-label">אבחנה מובילה (CNN)</div>
                    <div class="result-value">{predicted_description}</div>
                </div>
                """, unsafe_allow_html=True)
            with c2:
                st.markdown(f"""
                <div class="result-card" dir="rtl">
                    <div class="result-label">רמת ביטחון</div>
                    <div class="result-value">{local_confidence:.2f}%</div>
                </div>
                """, unsafe_allow_html=True)
            with c3:
                st.markdown(f"""
                <div class="result-card" dir="rtl">
                    <div class="result-label">הערכת זהירות</div>
                    <div class="result-value {risk_class}">{risk_text}</div>
                </div>
                """, unsafe_allow_html=True)

            st.markdown('<br>', unsafe_allow_html=True)
            st.markdown('<div class="soft-card" dir="rtl"><div class="section-title">התפלגות הסתברויות</div>', unsafe_allow_html=True)
            st.bar_chart({class_descriptions[class_labels[i]]: float(st.session_state.all_predictions[i]) for i in range(7)})
            st.markdown('</div>', unsafe_allow_html=True)

        st.markdown("""
        <div class="disclaimer-box">
            ⚠️ המערכת מיועדת למחקר, למידה ותמיכה בקבלת החלטות בלבד. היא אינה מחליפה אבחון של רופא עור.
        </div>
        """, unsafe_allow_html=True)

    with tab_report:
        if "initial_report_he" in st.session_state:
            st.markdown('<div class="section-title" dir="rtl">דו"ח קליני מורחב ומבוסס מודל שפה</div>', unsafe_allow_html=True)
            st.markdown(f'<div class="report-card">{st.session_state.initial_report_he}</div>', unsafe_allow_html=True)
            try:
                pred_text_list = [f"- {class_names_en[class_labels[i]]}: {float(st.session_state.all_predictions[i])*100:.2f}%" for i in range(7)]
                pdf_data = generate_pdf(pred_text_list, st.session_state.initial_report_en)
                st.download_button(label="📥 הורד דוח קליני רשמי (PDF באנגלית)", data=pdf_data, file_name="MedAI_Clinical_Report.pdf", mime="application/pdf")
            except Exception as pdf_error:
                st.warning(f"לא ניתן היה לייצר קובץ PDF להורדה: {pdf_error}")

    with tab_chat:
        st.markdown('<div class="section-title" dir="rtl">שאלות המשך לעוזר הרפואי</div>', unsafe_allow_html=True)
        st.markdown('<div class="muted-text" dir="rtl">אפשר לשאול בעברית על משמעות התוצאה, סימנים שדורשים בדיקה, או הצעד הבא.</div>', unsafe_allow_html=True)
        for message in st.session_state.chat_history[1:]:
            with st.chat_message(message["role"]):
                st.write(message["text"])
                
        user_question = st.chat_input("הקלד כאן את השאלה שלך")
        if user_question:
            with st.chat_message("user"):
                st.write(user_question)
            st.session_state.chat_history.append({"role": "user", "text": user_question})
            with st.spinner("⏳ מנסח תשובה..."):
                try:
                    conversation_context = f"""
                    You are continuing a conversation with a patient in Hebrew.
                    The original image was analyzed locally as {class_names_en[local_class]}.
                    Here is the history of the conversation:
                    """
                    for msg in st.session_state.chat_history[:-1]:
                        conversation_context += f"\n{msg['role']}: {msg['text']}"
                    conversation_context += f"\nPatient's new question: {user_question}\nPlease answer compassionately, clearly, and professionally in Hebrew. Never provide a definitive medical diagnosis."
                    reply = client.models.generate_content(model='gemini-2.5-flash', contents=[conversation_context, image])
                    with st.chat_message("assistant"):
                        st.write(reply.text)
                    st.session_state.chat_history.append({"role": "assistant", "text": reply.text})
                except Exception as e:
                    st.error(f"שגיאה בקבלת תשובה מהצ'אט: {e}")
else:
    st.markdown("""
    <div class="soft-card" dir="rtl">
        <div class="section-title">איך מתחילים?</div>
        <div class="muted-text">
            העלי תמונת JPG או PNG של נגע העור. לאחר ההעלאה המערכת תציג תוצאה מספרית, דוח קליני, ואפשרות לשאול שאלות המשך.
        </div>
    </div>
    """, unsafe_allow_html=True)